FROM mcr.microsoft.com/devcontainers/ruby:3

# Install the trmnlp local dev server.
# HTML rendering works out of the box; PNG rendering additionally requires
# Firefox and ImageMagick (omitted here to keep the image lean).
RUN gem install trmnl_preview
